<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.2" release="Mon Oct 24 12:27:06 2016 -0700">
<training_set datafile="memechip_out/seqs-centered" length="56">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="chr19:3099982-3100278" length="100" weight="1.000000" />
<sequence id="sequence_1" name="chr19:4812967-4813269" length="100" weight="1.000000" />
<sequence id="sequence_2" name="chr19:5715957-5716309" length="100" weight="1.000000" />
<sequence id="sequence_3" name="chr19:6260962-6261343" length="100" weight="1.000000" />
<sequence id="sequence_4" name="chr19:6954010-6954430" length="100" weight="1.000000" />
<sequence id="sequence_5" name="chr19:8567230-8567531" length="100" weight="1.000000" />
<sequence id="sequence_6" name="chr19:8858867-8859275" length="100" weight="1.000000" />
<sequence id="sequence_7" name="chr19:10525955-10526340" length="100" weight="1.000000" />
<sequence id="sequence_8" name="chr19:10831561-10831857" length="100" weight="1.000000" />
<sequence id="sequence_9" name="chr19:12134298-12134690" length="100" weight="1.000000" />
<sequence id="sequence_10" name="chr19:12820368-12820667" length="100" weight="1.000000" />
<sequence id="sequence_11" name="chr19:13301837-13302133" length="100" weight="1.000000" />
<sequence id="sequence_12" name="chr19:15869359-15869674" length="100" weight="1.000000" />
<sequence id="sequence_13" name="chr19:22304315-22304742" length="100" weight="1.000000" />
<sequence id="sequence_14" name="chr19:22337418-22337776" length="100" weight="1.000000" />
<sequence id="sequence_15" name="chr19:23666626-23666922" length="100" weight="1.000000" />
<sequence id="sequence_16" name="chr19:26510947-26511270" length="100" weight="1.000000" />
<sequence id="sequence_17" name="chr19:26682763-26683061" length="100" weight="1.000000" />
<sequence id="sequence_18" name="chr19:29644755-29645088" length="100" weight="1.000000" />
<sequence id="sequence_19" name="chr19:29820964-29821260" length="100" weight="1.000000" />
<sequence id="sequence_20" name="chr19:30128221-30128565" length="100" weight="1.000000" />
<sequence id="sequence_21" name="chr19:30664200-30664651" length="100" weight="1.000000" />
<sequence id="sequence_22" name="chr19:31811350-31811646" length="100" weight="1.000000" />
<sequence id="sequence_23" name="chr19:32710302-32710598" length="100" weight="1.000000" />
<sequence id="sequence_24" name="chr19:34241584-34241880" length="100" weight="1.000000" />
<sequence id="sequence_25" name="chr19:36111088-36111539" length="100" weight="1.000000" />
<sequence id="sequence_26" name="chr19:37755406-37755702" length="100" weight="1.000000" />
<sequence id="sequence_27" name="chr19:38329154-38329561" length="100" weight="1.000000" />
<sequence id="sequence_28" name="chr19:38775450-38775840" length="100" weight="1.000000" />
<sequence id="sequence_29" name="chr19:38880245-38880621" length="100" weight="1.000000" />
<sequence id="sequence_30" name="chr19:39527111-39527407" length="100" weight="1.000000" />
<sequence id="sequence_31" name="chr19:39676493-39676907" length="100" weight="1.000000" />
<sequence id="sequence_32" name="chr19:40363510-40363894" length="100" weight="1.000000" />
<sequence id="sequence_33" name="chr19:40737117-40737431" length="100" weight="1.000000" />
<sequence id="sequence_34" name="chr19:43306787-43307090" length="100" weight="1.000000" />
<sequence id="sequence_35" name="chr19:43487563-43487864" length="100" weight="1.000000" />
<sequence id="sequence_36" name="chr19:44148310-44148606" length="100" weight="1.000000" />
<sequence id="sequence_37" name="chr19:44754675-44755146" length="100" weight="1.000000" />
<sequence id="sequence_38" name="chr19:45047334-45047733" length="100" weight="1.000000" />
<sequence id="sequence_39" name="chr19:45469853-45470187" length="100" weight="1.000000" />
<sequence id="sequence_40" name="chr19:45694122-45694507" length="100" weight="1.000000" />
<sequence id="sequence_41" name="chr19:46137177-46137624" length="100" weight="1.000000" />
<sequence id="sequence_42" name="chr19:46369364-46369669" length="100" weight="1.000000" />
<sequence id="sequence_43" name="chr19:46389991-46390287" length="100" weight="1.000000" />
<sequence id="sequence_44" name="chr19:48939819-48940115" length="100" weight="1.000000" />
<sequence id="sequence_45" name="chr19:49467595-49467891" length="100" weight="1.000000" />
<sequence id="sequence_46" name="chr19:53073535-53073831" length="100" weight="1.000000" />
<sequence id="sequence_47" name="chr19:53753008-53753360" length="100" weight="1.000000" />
<sequence id="sequence_48" name="chr19:53925258-53925601" length="100" weight="1.000000" />
<sequence id="sequence_49" name="chr19:54325012-54325427" length="100" weight="1.000000" />
<sequence id="sequence_50" name="chr19:54960132-54960428" length="100" weight="1.000000" />
<sequence id="sequence_51" name="chr19:55876690-55877005" length="100" weight="1.000000" />
<sequence id="sequence_52" name="chr19:57193903-57194199" length="100" weight="1.000000" />
<sequence id="sequence_53" name="chr19:58103665-58103961" length="100" weight="1.000000" />
<sequence id="sequence_54" name="chr19:58313828-58314129" length="100" weight="1.000000" />
<sequence id="sequence_55" name="chr19:60883268-60883564" length="100" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.264</value>
<value letter_id="C">0.236</value>
<value letter_id="G">0.236</value>
<value letter_id="T">0.264</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme memechip_out/seqs-centered -oc memechip_out/meme_out -mod zoops -nmotifs 3 -minw 6 -maxw 20 -bfile memechip_out/background -dna -revcomp -nostatus </command_line>
<host>Sierra.local</host>
<type>zoops</type>
<nmotifs>3</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>6</min_width>
<max_width>20</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>56</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>56</num_sequences>
<num_positions>5600</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (3) found.</reason_for_stopping>
<background_frequencies source="memechip_out/background">
<alphabet_array>
<value letter_id="A">0.272</value>
<value letter_id="C">0.229</value>
<value letter_id="G">0.229</value>
<value letter_id="T">0.272</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="15" sites="30" ic="15.1" re="15.8" llr="328" e_value="8.7e-029" bayes_threshold="7.24227" elapsed_time="1.654386">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-70</value>
<value letter_id="C">54</value>
<value letter_id="G">92</value>
<value letter_id="T">-202</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-70</value>
<value letter_id="C">22</value>
<value letter_id="G">-178</value>
<value letter_id="T">88</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-302</value>
<value letter_id="C">-1155</value>
<value letter_id="G">168</value>
<value letter_id="T">-22</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-302</value>
<value letter_id="C">181</value>
<value letter_id="G">-178</value>
<value letter_id="T">-144</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1155</value>
<value letter_id="C">208</value>
<value letter_id="G">-277</value>
<value letter_id="T">-1155</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-44</value>
<value letter_id="C">161</value>
<value letter_id="G">-1155</value>
<value letter_id="T">-144</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1155</value>
<value letter_id="C">39</value>
<value letter_id="G">-1155</value>
<value letter_id="T">137</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1155</value>
<value letter_id="C">203</value>
<value letter_id="G">-178</value>
<value letter_id="T">-1155</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-103</value>
<value letter_id="C">-1155</value>
<value letter_id="G">-1155</value>
<value letter_id="T">167</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">14</value>
<value letter_id="C">-78</value>
<value letter_id="G">39</value>
<value letter_id="T">-3</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-202</value>
<value letter_id="C">131</value>
<value letter_id="G">54</value>
<value letter_id="T">-302</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-3</value>
<value letter_id="C">-277</value>
<value letter_id="G">-1155</value>
<value letter_id="T">137</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1155</value>
<value letter_id="C">-1155</value>
<value letter_id="G">213</value>
<value letter_id="T">-1155</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1155</value>
<value letter_id="C">-1155</value>
<value letter_id="G">208</value>
<value letter_id="T">-302</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-103</value>
<value letter_id="C">131</value>
<value letter_id="G">-78</value>
<value letter_id="T">-70</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.166667</value>
<value letter_id="C">0.333333</value>
<value letter_id="G">0.433333</value>
<value letter_id="T">0.066667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.166667</value>
<value letter_id="C">0.266667</value>
<value letter_id="G">0.066667</value>
<value letter_id="T">0.500000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.033333</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.733333</value>
<value letter_id="T">0.233333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.033333</value>
<value letter_id="C">0.800000</value>
<value letter_id="G">0.066667</value>
<value letter_id="T">0.100000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.966667</value>
<value letter_id="G">0.033333</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.200000</value>
<value letter_id="C">0.700000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.100000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.300000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.700000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.933333</value>
<value letter_id="G">0.066667</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.133333</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.866667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.300000</value>
<value letter_id="C">0.133333</value>
<value letter_id="G">0.300000</value>
<value letter_id="T">0.266667</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.066667</value>
<value letter_id="C">0.566667</value>
<value letter_id="G">0.333333</value>
<value letter_id="T">0.033333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.266667</value>
<value letter_id="C">0.033333</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.700000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.966667</value>
<value letter_id="T">0.033333</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.133333</value>
<value letter_id="C">0.566667</value>
<value letter_id="G">0.133333</value>
<value letter_id="T">0.166667</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[GC][TC][GT]CC[CA][TC]CT[AGT][CG][TA]GGC
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_54" position="34" strand="minus" pvalue="4.74e-10" >
<left_flank>ATGGAATCTG</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CCCTGTAGGT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_34" position="69" strand="plus" pvalue="2.08e-09" >
<left_flank>ataagatctg</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>cagtaggcat</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_3" position="36" strand="plus" pvalue="2.08e-09" >
<left_flank>aaaggatcca</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ctccaggggt</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_26" position="51" strand="plus" pvalue="2.73e-08" >
<left_flank>agaaactctg</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ctctttggac</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_13" position="10" strand="plus" pvalue="5.20e-08" >
<left_flank>AATGCTTCTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TAGTTCTAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_49" position="8" strand="plus" pvalue="6.35e-08" >
<left_flank>gagatttg</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ctctgtgggc</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_21" position="69" strand="minus" pvalue="8.66e-08" >
<left_flank>TGGTGCTTTT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AGCTTTTGGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_18" position="83" strand="plus" pvalue="1.03e-07" >
<left_flank>gaggaatctg</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>ct</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_14" position="47" strand="minus" pvalue="1.19e-07" >
<left_flank>TTATTGGACA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TACAGTGGGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_17" position="63" strand="plus" pvalue="2.11e-07" >
<left_flank>CCAATTCACT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TAACAAAGGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_48" position="7" strand="minus" pvalue="2.81e-07" >
<left_flank>ATAAGATCTG</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>CTCTGCG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_33" position="85" strand="plus" pvalue="3.61e-07" >
<left_flank>CTCTGCCACA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank></right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_4" position="13" strand="minus" pvalue="5.89e-07" >
<left_flank>GACTGGGGGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CTGTGCCAGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_46" position="69" strand="minus" pvalue="1.29e-06" >
<left_flank>AGGGGATCTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CTTCACAGAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_16" position="17" strand="plus" pvalue="2.39e-06" >
<left_flank>tcaggctatg</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>AGGAGGTTCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_38" position="73" strand="minus" pvalue="6.54e-06" >
<left_flank>AGTCCCTTAG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ACCCACCCCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_12" position="46" strand="plus" pvalue="6.54e-06" >
<left_flank>TAAAGCTTTG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>GAGAAGAAGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_40" position="13" strand="plus" pvalue="8.40e-06" >
<left_flank>ATTCACAGTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CAATGGATGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_23" position="74" strand="plus" pvalue="8.40e-06" >
<left_flank>CATGTTGAAA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>