<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!-- http://zlab.bu.edu/~phaverty/SupplementalData/CisML/cisml.dtd -->
<!DOCTYPE cis-element-search[
<!ELEMENT cis-element-search (program-name, parameters, (pattern | multi-pattern-scan)*)>
<!ELEMENT program-name (#PCDATA)>
<!ELEMENT parameters (
  pattern-file, 
  sequence-file, 
  background-seq-file?,
  pattern-pvalue-cutoff?,
  sequence-pvalue-cutoff?,
  site-pvalue-cutoff?,
  sequence-filtering,
  ANY*
 )>
<!ELEMENT command-line (#PCDATA)>
<!ELEMENT pattern-file (#PCDATA)>
<!ELEMENT sequence-file (#PCDATA)>
<!ELEMENT background-seq-file (#PCDATA)>
<!ELEMENT pattern-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-pvalue-cutoff (#PCDATA)>
<!ELEMENT site-pvalue-cutoff (#PCDATA)>
<!ELEMENT sequence-filtering EMPTY>
<!ELEMENT multi-pattern-scan (pattern+, ANY*)>
<!ELEMENT pattern (scanned-sequence+, ANY*)>
<!ELEMENT scanned-sequence (matched-element*, ANY*)>
<!ELEMENT matched-element (sequence)>
<!ELEMENT sequence (#PCDATA)>
<!ATTLIST cis-element-search
xmlns:xsi CDATA #IMPLIED
xmlns:mem CDATA #IMPLIED
xsi:schemaLocation CDATA #IMPLIED
>
<!ATTLIST sequence-filtering
on-off CDATA #REQUIRED
type CDATA #IMPLIED
>
<!ATTLIST multi-pattern-scan
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
>
<!ATTLIST pattern
accession CDATA #REQUIRED
name CDATA #REQUIRED
pvalue CDATA #IMPLIED
score CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST scanned-sequence
accession CDATA #REQUIRED
name CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
length CDATA #IMPLIED
db CDATA #IMPLIED
lsid CDATA #IMPLIED
>
<!ATTLIST matched-element
start CDATA #REQUIRED
stop CDATA #REQUIRED
score CDATA #IMPLIED
pvalue CDATA #IMPLIED
clusterid CDATA #IMPLIED
>

]>
<cis-element-search
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://zlab.bu.edu/schema/cisml cisml.xsd"
  xmlns="http://zlab.bu.edu/schema/cisml"
  xmlns:mem="http://noble.gs.washington.edu/meme"
>
<program-name>fimo</program-name>
<parameters>
<pattern-file>memechip_out/meme_out/meme.xml</pattern-file>
<sequence-file>memechip_out/gain.fa</sequence-file>
<site-pvalue-cutoff>0.0001</site-pvalue-cutoff>
<sequence-filtering on-off="off"/>
</parameters>
<pattern accession="2" name="2">
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="3348007" stop="3347988" score="23.7172" pvalue="8.5e-09">
<sequence>TATACCTCCAGCTCCATGAG</sequence>
<mem:qvalue>8.82e-05</mem:qvalue>
</matched-element>
<matched-element start="3348081" stop="3348062" score="4.69697" pvalue="7.76e-05">
<sequence>AATGTTTCCTGCTCTTGCAG</sequence>
<mem:qvalue>0.182</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="3619589" stop="3619570" score="19.9394" pvalue="1.12e-07">
<sequence>TGACAGTCCAGTTCCAAGGG</sequence>
<mem:qvalue>0.000624</mem:qvalue>
</matched-element>
<matched-element start="3619652" stop="3619633" score="7.59596" pvalue="2.93e-05">
<sequence>ATTGGCTGCTCTTCTAGAGG</sequence>
<mem:qvalue>0.101</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="4255908" stop="4255927" score="17.2424" pvalue="5.02e-07">
<sequence>accgactgctcttccagagg</sequence>
<mem:qvalue>0.00214</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="4279655" stop="4279674" score="21.0505" pvalue="5.59e-08">
<sequence>tatttctccagttccaagga</sequence>
<mem:qvalue>0.000338</mem:qvalue>
</matched-element>
<matched-element start="4279622" stop="4279603" score="4.39394" pvalue="8.55e-05">
<sequence>ATTGACACCAGTCCCTTGCA</sequence>
<mem:qvalue>0.194</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="5087861" stop="5087880" score="18.8081" pvalue="2.16e-07">
<sequence>TCTGTCTCCTGCCCcatgcg</sequence>
<mem:qvalue>0.00105</mem:qvalue>
</matched-element>
<matched-element start="5087803" stop="5087822" score="5" pvalue="7.04e-05">
<sequence>ACAGATTCCTGTCCCATGTA</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="5129888" stop="5129907" score="21.7778" pvalue="3.46e-08">
<sequence>actgtctgctcttccagggg</sequence>
<mem:qvalue>0.000251</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="5428264" stop="5428283" score="31.0404" pvalue="3.13e-12">
<sequence>tgtgactccagttccagggg</sequence>
<mem:qvalue>2.28e-07</mem:qvalue>
</matched-element>
<matched-element start="5428195" stop="5428214" score="5.0202" pvalue="6.99e-05">
<sequence>attaattattcttccagagg</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="5998414" stop="5998395" score="25.9091" pvalue="1.33e-09">
<sequence>TGTACCTCCAGCTCCAGGCG</sequence>
<mem:qvalue>1.93e-05</mem:qvalue>
</matched-element>
<matched-element start="5998479" stop="5998460" score="5.51515" pvalue="5.95e-05">
<sequence>GCACACTGCTCTTCCAAGAG</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="10182785" stop="10182766" score="5.29293" pvalue="6.4e-05">
<sequence>ACTCAGGCTACTTCCAGCGG</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="10520493" stop="10520512" score="13.9899" pvalue="2.37e-06">
<sequence>actgcttgctcttccagagg</sequence>
<mem:qvalue>0.00905</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="18588416" stop="18588435" score="22.0101" pvalue="2.95e-08">
<sequence>tgtaactctagtccctgggg</sequence>
<mem:qvalue>0.000238</mem:qvalue>
</matched-element>
<matched-element start="18588351" stop="18588370" score="14.9192" pvalue="1.56e-06">
<sequence>actggctgctcttccagggg</sequence>
<mem:qvalue>0.00628</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="22916060" stop="22916041" score="21.3232" pvalue="4.68e-08">
<sequence>ACTCACTGCAGCTCCAGGGA</sequence>
<mem:qvalue>0.000309</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="23225328" stop="23225347" score="5.28283" pvalue="6.42e-05">
<sequence>agcacttgctgctctttaag</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="25334552" stop="25334571" score="23.4747" pvalue="1.02e-08">
<sequence>tataaagccagttccagggg</sequence>
<mem:qvalue>9.29e-05</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="27683602" stop="27683621" score="27.9495" pvalue="1.69e-10">
<sequence>tgtaactccagctcaagggg</sequence>
<mem:qvalue>3.07e-06</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="30828060" stop="30828041" score="19.5253" pvalue="1.43e-07">
<sequence>ATTAACTTCAGCTCTAGGGA</sequence>
<mem:qvalue>0.000742</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="31046766" stop="31046785" score="28.8182" pvalue="6.13e-11">
<sequence>agtaactccagctccatggg</sequence>
<mem:qvalue>1.48e-06</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="37209810" stop="37209829" score="7.15152" pvalue="3.42e-05">
<sequence>TGTTTATCCAGTGCCATGCA</sequence>
<mem:qvalue>0.113</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="41258879" stop="41258898" score="24.303" pvalue="5.35e-09">
<sequence>tgtaactcctcttctaggag</sequence>
<mem:qvalue>6.47e-05</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="41952605" stop="41952624" score="18.4747" pvalue="2.6e-07">
<sequence>AGCACttccaggtctagggg</sequence>
<mem:qvalue>0.00118</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="42655298" stop="42655279" score="5.20202" pvalue="6.59e-05">
<sequence>TGCACCTTCAGGCCTGGGGA</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="43961359" stop="43961378" score="30.0505" pvalue="1.19e-11">
<sequence>tgtaactccagttctagggg</sequence>
<mem:qvalue>4.34e-07</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="45116882" stop="45116901" score="7.82828" pvalue="2.7e-05">
<sequence>TCTATCTCCTGTCCAATGCC</sequence>
<mem:qvalue>0.0979</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="46029131" stop="46029150" score="5.08081" pvalue="6.86e-05">
<sequence>tatgcctattgctcttggag</sequence>
<mem:qvalue>0.17</mem:qvalue>
</matched-element>
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
</scanned-sequence>
<scanned-sequence accession="chr19" name="chr19">
<matched-element start="47264556" stop="47264537" score="5.88889" pvalue="5.26e-05">
<sequence>GTAACATCCAGCCCCAGGGA</sequence>
<mem:qvalue>0.166</mem:qvalue>
</matched-element>
</scanned-sequence>
<mem:has-qvalues>yes</mem:has-qvalues>
</pattern>
</cis-element-search>
